# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Synthwaves < Formula
  desc "synthwaves.fm CLI - manage your music library from the terminal"
  homepage "https://synthwaves.fm"
  version "0.1.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/leopolicastro/synthwaves.fm-cli/releases/download/v0.1.5/synthwaves_0.1.5_darwin_amd64.tar.gz"
      sha256 "b9d099d9c7d0a021016e765779a887b1e977df09fb6af9b66780d6a25556eb08"

      define_method(:install) do
        bin.install "synthwaves"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/leopolicastro/synthwaves.fm-cli/releases/download/v0.1.5/synthwaves_0.1.5_darwin_arm64.tar.gz"
      sha256 "1528f335d585e8b5cb15c12c31a71f1766596eb9f518723350901e3144672211"

      define_method(:install) do
        bin.install "synthwaves"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/leopolicastro/synthwaves.fm-cli/releases/download/v0.1.5/synthwaves_0.1.5_linux_amd64.tar.gz"
      sha256 "c5327a9697e33657e7b822a013ddab60984a050cddd8a2d0ed3a653e2a77215d"
      define_method(:install) do
        bin.install "synthwaves"
      end
    end
  end

  test do
    system "#{bin}/synthwaves", "version"
  end
end
