# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Synthwaves < Formula
  desc "synthwaves.fm CLI - manage your music library from the terminal"
  homepage "https://synthwaves.fm"
  version "0.1.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/leopolicastro/synthwaves.fm-cli/releases/download/v0.1.4/synthwaves_0.1.4_darwin_amd64.tar.gz"
      sha256 "659edd050187a7e7bde5422cebdaf6306dee2df624027ce62517c0407a307dc4"

      define_method(:install) do
        bin.install "synthwaves"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/leopolicastro/synthwaves.fm-cli/releases/download/v0.1.4/synthwaves_0.1.4_darwin_arm64.tar.gz"
      sha256 "2534a5baf1002c8abbf682a3b6195b8db017a8ecd57d195a0e90e94ebdfd17d1"

      define_method(:install) do
        bin.install "synthwaves"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/leopolicastro/synthwaves.fm-cli/releases/download/v0.1.4/synthwaves_0.1.4_linux_amd64.tar.gz"
      sha256 "9801899cb1e7333112a7f1f5d0f50ee54160ccf39ed50647b111186d9d403896"
      define_method(:install) do
        bin.install "synthwaves"
      end
    end
  end

  test do
    system "#{bin}/synthwaves", "version"
  end
end
